### ISSUE TITLE
Will Pinecone ever have HTTP and Websocket support?

### ISSUE THREAD

**Issue by CodeFromCirc** [wmww/Pinecone#19]
A friend of mine is making a lib made in Pinecone for a chat service. So will Pinecone ever have support to even attempt to make that?

**Comment by wsKilljoy** [comment]
Hard to say. Pinecone isn't under active development right now, so if you want that, you may have to bind it yourself with cppCode(). However, I'm not @wmww, so I may be incorrect.

**Comment by wmww** [comment]
You could try to use a C/C++ library (see the 'Linking with C++' section in https://github.com/wmww/Pinecone/blob/master/tutorials/7_temporary_hacks.md). I wouldn't recommend putting too much work into a Pinecone project at this point, since (as @wsKilljoy pointed out), I am no longer actively developing Pinecone.

**Comment by CodeFromCirc** [comment]
I see, thanks
